apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hola-mundo
  template:
    metadata:
      labels:
        app: hola-mundo
    spec:
      containers:
      - name: app-container
        image: <nombre_de_usuario_en_docker_hub>/<nombre_del_repositorio>:<tag>
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred

