apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hola-mundo
  template:
    metadata:
      labels:
        app: hola-mundo
    spec:
      containers:
      - name: app-container
        image: mariocr73/py-webapp:v1
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred
