apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: Opaque
data:
  username: <valor_del_usuario_en_base64>
  password: <valor_de_la_contraseña_en_base64>
  email: <valor_del_correo_en_base64>
